FROM golang:1.18-buster AS build

WORKDIR /app

ENV GO111MODULE=on

COPY ./app-integration-worker ./app-integration-worker
COPY ./shared ./shared
COPY ./python-scripts ./python-scripts

RUN cd shared && go mod download

RUN cd app-integration-worker && go mod download
RUN cd app-integration-worker && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -mod=mod -o /go/bin/app-integration-worker main.go

FROM alpine

RUN addgroup -S app && adduser -S app -G app

COPY --from=build /go/bin/app-integration-worker /app/
COPY --from=build /app/app-integration-worker/.env /app/.env
COPY --from=build /app/shared/.env /app/shared/.env

WORKDIR /app
RUN chown -R app:app /app
USER app

CMD ["./app-integration-worker"]
