// Code generated by MockGen. DO NOT EDIT.
// Source: generator.go
//
// Generated by this command:
//
//	mockgen -source=generator.go -destination=mocks/mock_generator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	generators "github.com/verasthiago/verancial/app-integration-worker/pkg/generators"
	types "github.com/verasthiago/verancial/app-integration-worker/pkg/types"
	constants "github.com/verasthiago/verancial/shared/constants"
	models "github.com/verasthiago/verancial/shared/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAppReport is a mock of AppReport interface.
type MockAppReport struct {
	ctrl     *gomock.Controller
	recorder *MockAppReportMockRecorder
	isgomock struct{}
}

// MockAppReportMockRecorder is the mock recorder for MockAppReport.
type MockAppReportMockRecorder struct {
	mock *MockAppReport
}

// NewMockAppReport creates a new mock instance.
func NewMockAppReport(ctrl *gomock.Controller) *MockAppReport {
	mock := &MockAppReport{ctrl: ctrl}
	mock.recorder = &MockAppReportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppReport) EXPECT() *MockAppReportMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockAppReport) Generate(transactions []*models.Transaction) (types.AppReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", transactions)
	ret0, _ := ret[0].(types.AppReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockAppReportMockRecorder) Generate(transactions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockAppReport)(nil).Generate), transactions)
}

// GetLastTransaction mocks base method.
func (m *MockAppReport) GetLastTransaction(financialAppCredentials *models.FinancialAppCredentials, bankId, lastTransactionDate string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTransaction", financialAppCredentials, bankId, lastTransactionDate)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTransaction indicates an expected call of GetLastTransaction.
func (mr *MockAppReportMockRecorder) GetLastTransaction(financialAppCredentials, bankId, lastTransactionDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTransaction", reflect.TypeOf((*MockAppReport)(nil).GetLastTransaction), financialAppCredentials, bankId, lastTransactionDate)
}

// Submit mocks base method.
func (m *MockAppReport) Submit(user *models.User, appReport types.AppReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", user, appReport)
	ret0, _ := ret[0].(error)
	return ret0
}

// Submit indicates an expected call of Submit.
func (mr *MockAppReportMockRecorder) Submit(user, appReport any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockAppReport)(nil).Submit), user, appReport)
}

// MockAppReportGeneratorFactory is a mock of AppReportGeneratorFactory interface.
type MockAppReportGeneratorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAppReportGeneratorFactoryMockRecorder
	isgomock struct{}
}

// MockAppReportGeneratorFactoryMockRecorder is the mock recorder for MockAppReportGeneratorFactory.
type MockAppReportGeneratorFactoryMockRecorder struct {
	mock *MockAppReportGeneratorFactory
}

// NewMockAppReportGeneratorFactory creates a new mock instance.
func NewMockAppReportGeneratorFactory(ctrl *gomock.Controller) *MockAppReportGeneratorFactory {
	mock := &MockAppReportGeneratorFactory{ctrl: ctrl}
	mock.recorder = &MockAppReportGeneratorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppReportGeneratorFactory) EXPECT() *MockAppReportGeneratorFactoryMockRecorder {
	return m.recorder
}

// GetAppReportGenerator mocks base method.
func (m *MockAppReportGeneratorFactory) GetAppReportGenerator(appName constants.AppID) (generators.AppReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppReportGenerator", appName)
	ret0, _ := ret[0].(generators.AppReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppReportGenerator indicates an expected call of GetAppReportGenerator.
func (mr *MockAppReportGeneratorFactoryMockRecorder) GetAppReportGenerator(appName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppReportGenerator", reflect.TypeOf((*MockAppReportGeneratorFactory)(nil).GetAppReportGenerator), appName)
}
