version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/dockerfile
    ports:
      - 8080:8080

  login:
    container_name: login
    build:
      context: .
      dockerfile: login/dockerfile
    ports:
      - 8081:8080

  worker-redis:
    image: "redis"
    ports:
      - "6379:6379"

  # Local database removed - now using Supabase
  # To use local database for development, uncomment the following:
  # database:
  #   container_name: database
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB_EXTENSIONS=hstore,uuid-ossp
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
