FROM golang:1.23-bookworm AS build

WORKDIR /app

ENV GO111MODULE=on

COPY ./login ./login
COPY ./shared ./shared

RUN cd shared && go mod download

RUN cd login && go mod download
RUN cd login && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -mod=mod -o /go/bin/login main.go

FROM alpine

RUN addgroup -S app && adduser -S app -G app

COPY --from=build /go/bin/login /app/
COPY --from=build /app/login/.env /app/.env
COPY --from=build --chown=app:app /app/shared/.env /shared/.env

WORKDIR /app
RUN chown -R app:app /app
USER app

CMD ["./login"]
