// Code generated by MockGen. DO NOT EDIT.
// Source: builder.go
//
// Generated by this command:
//
//	mockgen -source=builder.go -destination=mocks/mock_builder.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	builder "github.com/verasthiago/verancial/login/pkg/builder"
	flags "github.com/verasthiago/verancial/shared/flags"
	repository "github.com/verasthiago/verancial/shared/repository"
	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
	isgomock struct{}
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder {
	mock := &MockBuilder{ctrl: ctrl}
	mock.recorder = &MockBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	return m.recorder
}

// GetFlags mocks base method.
func (m *MockBuilder) GetFlags() *builder.Flags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlags")
	ret0, _ := ret[0].(*builder.Flags)
	return ret0
}

// GetFlags indicates an expected call of GetFlags.
func (mr *MockBuilderMockRecorder) GetFlags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlags", reflect.TypeOf((*MockBuilder)(nil).GetFlags))
}

// GetLog mocks base method.
func (m *MockBuilder) GetLog() *zap.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLog")
	ret0, _ := ret[0].(*zap.Logger)
	return ret0
}

// GetLog indicates an expected call of GetLog.
func (mr *MockBuilderMockRecorder) GetLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLog", reflect.TypeOf((*MockBuilder)(nil).GetLog))
}

// GetRepository mocks base method.
func (m *MockBuilder) GetRepository() repository.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository")
	ret0, _ := ret[0].(repository.Repository)
	return ret0
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockBuilderMockRecorder) GetRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockBuilder)(nil).GetRepository))
}

// GetSharedFlags mocks base method.
func (m *MockBuilder) GetSharedFlags() *flags.SharedFlags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedFlags")
	ret0, _ := ret[0].(*flags.SharedFlags)
	return ret0
}

// GetSharedFlags indicates an expected call of GetSharedFlags.
func (mr *MockBuilderMockRecorder) GetSharedFlags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedFlags", reflect.TypeOf((*MockBuilder)(nil).GetSharedFlags))
}

// InitBuilder mocks base method.
func (m *MockBuilder) InitBuilder(loginEnvConfigFile, sharedEnvConfigFile *flags.EnvFileConfig) builder.Builder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitBuilder", loginEnvConfigFile, sharedEnvConfigFile)
	ret0, _ := ret[0].(builder.Builder)
	return ret0
}

// InitBuilder indicates an expected call of InitBuilder.
func (mr *MockBuilderMockRecorder) InitBuilder(loginEnvConfigFile, sharedEnvConfigFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitBuilder", reflect.TypeOf((*MockBuilder)(nil).InitBuilder), loginEnvConfigFile, sharedEnvConfigFile)
}
