// Code generated by MockGen. DO NOT EDIT.
// Source: report.go
//
// Generated by this command:
//
//	mockgen -source=report.go -destination=mocks/mock_report.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	report "github.com/verasthiago/verancial/data-process-worker/pkg/report"
	constants "github.com/verasthiago/verancial/shared/constants"
	models "github.com/verasthiago/verancial/shared/models"
	types "github.com/verasthiago/verancial/shared/types"
	gomock "go.uber.org/mock/gomock"
)

// MockBankReport is a mock of BankReport interface.
type MockBankReport struct {
	ctrl     *gomock.Controller
	recorder *MockBankReportMockRecorder
	isgomock struct{}
}

// MockBankReportMockRecorder is the mock recorder for MockBankReport.
type MockBankReportMockRecorder struct {
	mock *MockBankReport
}

// NewMockBankReport creates a new mock instance.
func NewMockBankReport(ctrl *gomock.Controller) *MockBankReport {
	mock := &MockBankReport{ctrl: ctrl}
	mock.recorder = &MockBankReportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankReport) EXPECT() *MockBankReportMockRecorder {
	return m.recorder
}

// LoadFromCSV mocks base method.
func (m *MockBankReport) LoadFromCSV(csvPath string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFromCSV", csvPath)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadFromCSV indicates an expected call of LoadFromCSV.
func (mr *MockBankReportMockRecorder) LoadFromCSV(csvPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFromCSV", reflect.TypeOf((*MockBankReport)(nil).LoadFromCSV), csvPath)
}

// Process mocks base method.
func (m *MockBankReport) Process(bankTransactions []any, payload *types.ReportProcessQueuePayload, lastDbTransaction *models.Transaction) ([]*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", bankTransactions, payload, lastDbTransaction)
	ret0, _ := ret[0].([]*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockBankReportMockRecorder) Process(bankTransactions, payload, lastDbTransaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockBankReport)(nil).Process), bankTransactions, payload, lastDbTransaction)
}

// MockReportProcessorFactory is a mock of ReportProcessorFactory interface.
type MockReportProcessorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockReportProcessorFactoryMockRecorder
	isgomock struct{}
}

// MockReportProcessorFactoryMockRecorder is the mock recorder for MockReportProcessorFactory.
type MockReportProcessorFactoryMockRecorder struct {
	mock *MockReportProcessorFactory
}

// NewMockReportProcessorFactory creates a new mock instance.
func NewMockReportProcessorFactory(ctrl *gomock.Controller) *MockReportProcessorFactory {
	mock := &MockReportProcessorFactory{ctrl: ctrl}
	mock.recorder = &MockReportProcessorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportProcessorFactory) EXPECT() *MockReportProcessorFactoryMockRecorder {
	return m.recorder
}

// GetReportProcessor mocks base method.
func (m *MockReportProcessorFactory) GetReportProcessor(bankName constants.BankId) (report.BankReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportProcessor", bankName)
	ret0, _ := ret[0].(report.BankReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportProcessor indicates an expected call of GetReportProcessor.
func (mr *MockReportProcessorFactoryMockRecorder) GetReportProcessor(bankName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportProcessor", reflect.TypeOf((*MockReportProcessorFactory)(nil).GetReportProcessor), bankName)
}
