// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	models "github.com/verasthiago/verancial/shared/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateTransactionInBatches mocks base method.
func (m *MockRepository) CreateTransactionInBatches(transacions []*models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionInBatches", transacions)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactionInBatches indicates an expected call of CreateTransactionInBatches.
func (mr *MockRepositoryMockRecorder) CreateTransactionInBatches(transacions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionInBatches", reflect.TypeOf((*MockRepository)(nil).CreateTransactionInBatches), transacions)
}

// CreateUniqueTransactionInBatches mocks base method.
func (m *MockRepository) CreateUniqueTransactionInBatches(transactions []*models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUniqueTransactionInBatches", transactions)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUniqueTransactionInBatches indicates an expected call of CreateUniqueTransactionInBatches.
func (mr *MockRepositoryMockRecorder) CreateUniqueTransactionInBatches(transactions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUniqueTransactionInBatches", reflect.TypeOf((*MockRepository)(nil).CreateUniqueTransactionInBatches), transactions)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), user)
}

// DeleteUser mocks base method.
func (m *MockRepository) DeleteUser(userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockRepositoryMockRecorder) DeleteUser(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockRepository)(nil).DeleteUser), userId)
}

// GetAllTransactionsFromUserBankAfterDate mocks base method.
func (m *MockRepository) GetAllTransactionsFromUserBankAfterDate(userId, BankId string, lastTransaction time.Time) ([]*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTransactionsFromUserBankAfterDate", userId, BankId, lastTransaction)
	ret0, _ := ret[0].([]*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTransactionsFromUserBankAfterDate indicates an expected call of GetAllTransactionsFromUserBankAfterDate.
func (mr *MockRepositoryMockRecorder) GetAllTransactionsFromUserBankAfterDate(userId, BankId, lastTransaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTransactionsFromUserBankAfterDate", reflect.TypeOf((*MockRepository)(nil).GetAllTransactionsFromUserBankAfterDate), userId, BankId, lastTransaction)
}

// GetBankAccountById mocks base method.
func (m *MockRepository) GetBankAccountById(bankId, userId string) (*models.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankAccountById", bankId, userId)
	ret0, _ := ret[0].(*models.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankAccountById indicates an expected call of GetBankAccountById.
func (mr *MockRepositoryMockRecorder) GetBankAccountById(bankId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankAccountById", reflect.TypeOf((*MockRepository)(nil).GetBankAccountById), bankId, userId)
}

// GetLastTransactionFromUserBank mocks base method.
func (m *MockRepository) GetLastTransactionFromUserBank(userId, BankId string) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTransactionFromUserBank", userId, BankId)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTransactionFromUserBank indicates an expected call of GetLastTransactionFromUserBank.
func (mr *MockRepositoryMockRecorder) GetLastTransactionFromUserBank(userId, BankId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTransactionFromUserBank", reflect.TypeOf((*MockRepository)(nil).GetLastTransactionFromUserBank), userId, BankId)
}

// GetTransactionCountFromUserBank mocks base method.
func (m *MockRepository) GetTransactionCountFromUserBank(userId, BankId string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionCountFromUserBank", userId, BankId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionCountFromUserBank indicates an expected call of GetTransactionCountFromUserBank.
func (mr *MockRepositoryMockRecorder) GetTransactionCountFromUserBank(userId, BankId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionCountFromUserBank", reflect.TypeOf((*MockRepository)(nil).GetTransactionCountFromUserBank), userId, BankId)
}

// GetTransactions mocks base method.
func (m *MockRepository) GetTransactions(userId, bankId string, limit, offset int, filter *models.TransactionFilter) ([]*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", userId, bankId, limit, offset, filter)
	ret0, _ := ret[0].([]*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockRepositoryMockRecorder) GetTransactions(userId, bankId, limit, offset, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockRepository)(nil).GetTransactions), userId, bankId, limit, offset, filter)
}

// GetUserBankAccounts mocks base method.
func (m *MockRepository) GetUserBankAccounts(userId string) ([]*models.UserBankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBankAccounts", userId)
	ret0, _ := ret[0].([]*models.UserBankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBankAccounts indicates an expected call of GetUserBankAccounts.
func (mr *MockRepositoryMockRecorder) GetUserBankAccounts(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBankAccounts", reflect.TypeOf((*MockRepository)(nil).GetUserBankAccounts), userId)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), email)
}

// GetUserByID mocks base method.
func (m *MockRepository) GetUserByID(id string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryMockRecorder) GetUserByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepository)(nil).GetUserByID), id)
}

// GetUserDashboardStats mocks base method.
func (m *MockRepository) GetUserDashboardStats(userId string) (*models.UserDashboardStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDashboardStats", userId)
	ret0, _ := ret[0].(*models.UserDashboardStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDashboardStats indicates an expected call of GetUserDashboardStats.
func (mr *MockRepositoryMockRecorder) GetUserDashboardStats(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDashboardStats", reflect.TypeOf((*MockRepository)(nil).GetUserDashboardStats), userId)
}

// MigrateBankAccount mocks base method.
func (m *MockRepository) MigrateBankAccount(model *models.BankAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateBankAccount", model)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateBankAccount indicates an expected call of MigrateBankAccount.
func (mr *MockRepositoryMockRecorder) MigrateBankAccount(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateBankAccount", reflect.TypeOf((*MockRepository)(nil).MigrateBankAccount), model)
}

// MigrateTransaction mocks base method.
func (m *MockRepository) MigrateTransaction(model *models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateTransaction", model)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateTransaction indicates an expected call of MigrateTransaction.
func (mr *MockRepositoryMockRecorder) MigrateTransaction(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateTransaction", reflect.TypeOf((*MockRepository)(nil).MigrateTransaction), model)
}

// MigrateUser mocks base method.
func (m *MockRepository) MigrateUser(model *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateUser", model)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateUser indicates an expected call of MigrateUser.
func (mr *MockRepositoryMockRecorder) MigrateUser(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateUser", reflect.TypeOf((*MockRepository)(nil).MigrateUser), model)
}

// MigrateUserBankAccount mocks base method.
func (m *MockRepository) MigrateUserBankAccount(model *models.UserBankAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateUserBankAccount", model)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateUserBankAccount indicates an expected call of MigrateUserBankAccount.
func (mr *MockRepositoryMockRecorder) MigrateUserBankAccount(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateUserBankAccount", reflect.TypeOf((*MockRepository)(nil).MigrateUserBankAccount), model)
}

// UpdateUser mocks base method.
func (m *MockRepository) UpdateUser(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockRepositoryMockRecorder) UpdateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockRepository)(nil).UpdateUser), user)
}
