// Code generated by MockGen. DO NOT EDIT.
// Source: builder.go
//
// Generated by this command:
//
//	mockgen -source=builder.go -destination=mocks/mock_builder.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	builder "github.com/verasthiago/verancial/app-integration-worker/pkg/builder"
	generators "github.com/verasthiago/verancial/app-integration-worker/pkg/generators"
	flags "github.com/verasthiago/verancial/shared/flags"
	repository "github.com/verasthiago/verancial/shared/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
	isgomock struct{}
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder {
	mock := &MockBuilder{ctrl: ctrl}
	mock.recorder = &MockBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	return m.recorder
}

// GetAppReportGeneratorFactory mocks base method.
func (m *MockBuilder) GetAppReportGeneratorFactory() generators.AppReportGeneratorFactory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppReportGeneratorFactory")
	ret0, _ := ret[0].(generators.AppReportGeneratorFactory)
	return ret0
}

// GetAppReportGeneratorFactory indicates an expected call of GetAppReportGeneratorFactory.
func (mr *MockBuilderMockRecorder) GetAppReportGeneratorFactory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppReportGeneratorFactory", reflect.TypeOf((*MockBuilder)(nil).GetAppReportGeneratorFactory))
}

// GetFlags mocks base method.
func (m *MockBuilder) GetFlags() *builder.Flags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlags")
	ret0, _ := ret[0].(*builder.Flags)
	return ret0
}

// GetFlags indicates an expected call of GetFlags.
func (mr *MockBuilderMockRecorder) GetFlags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlags", reflect.TypeOf((*MockBuilder)(nil).GetFlags))
}

// GetRepository mocks base method.
func (m *MockBuilder) GetRepository() repository.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository")
	ret0, _ := ret[0].(repository.Repository)
	return ret0
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockBuilderMockRecorder) GetRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockBuilder)(nil).GetRepository))
}

// GetSharedFlags mocks base method.
func (m *MockBuilder) GetSharedFlags() *flags.SharedFlags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedFlags")
	ret0, _ := ret[0].(*flags.SharedFlags)
	return ret0
}

// GetSharedFlags indicates an expected call of GetSharedFlags.
func (mr *MockBuilderMockRecorder) GetSharedFlags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedFlags", reflect.TypeOf((*MockBuilder)(nil).GetSharedFlags))
}

// InitBuilder mocks base method.
func (m *MockBuilder) InitBuilder(appIntegrationEnvConfigFile, sharedEnvFileConfig *flags.EnvFileConfig) builder.Builder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitBuilder", appIntegrationEnvConfigFile, sharedEnvFileConfig)
	ret0, _ := ret[0].(builder.Builder)
	return ret0
}

// InitBuilder indicates an expected call of InitBuilder.
func (mr *MockBuilderMockRecorder) InitBuilder(appIntegrationEnvConfigFile, sharedEnvFileConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitBuilder", reflect.TypeOf((*MockBuilder)(nil).InitBuilder), appIntegrationEnvConfigFile, sharedEnvFileConfig)
}
