// Code generated by MockGen. DO NOT EDIT.
// Source: task_inteface.go
//
// Generated by this command:
//
//	mockgen -source=task_inteface.go -destination=mocks/mock_task.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	types "github.com/verasthiago/verancial/shared/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
	isgomock struct{}
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// CreateReportAsync mocks base method.
func (m *MockTask) CreateReportAsync(payload types.ReportProcessQueuePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReportAsync", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReportAsync indicates an expected call of CreateReportAsync.
func (mr *MockTaskMockRecorder) CreateReportAsync(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReportAsync", reflect.TypeOf((*MockTask)(nil).CreateReportAsync), payload)
}

// UpdateAppAsync mocks base method.
func (m *MockTask) UpdateAppAsync(payload types.AppIntegrationQueuePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppAsync", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppAsync indicates an expected call of UpdateAppAsync.
func (mr *MockTaskMockRecorder) UpdateAppAsync(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppAsync", reflect.TypeOf((*MockTask)(nil).UpdateAppAsync), payload)
}
