FROM golang:1.23-bookworm AS build

WORKDIR /app

ENV GO111MODULE=on

COPY ./api ./api
COPY ./shared ./shared

RUN cd shared && go mod download

RUN cd api && go mod download
RUN cd api && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -mod=mod -o /go/bin/api main.go

FROM alpine

RUN addgroup -S app && adduser -S app -G app

COPY --from=build /go/bin/api /app/
COPY --from=build /app/api/.env /app/.env
COPY --from=build --chown=app:app /app/shared/.env /shared/.env

WORKDIR /app
RUN chown -R app:app /app
USER app

CMD ["./api"]
